### ISSUE TITLE
Merge back into libbsd upstream?

### ISSUE THREAD

**Issue by guillemj** [JackieXie168/libbsd#4]
Hi!

I just found out about this project some time ago, and was wondering why the needed changes were not proposed to libbsd upstream? The project is not intended to be just for GNU systems, but for anything that lacks the BSD alternatives. If this is not clear somewhere I'm happy to clarify it.

**Comment by guillemj** [comment]
Hi!

Just to mention that the current main branch in git now build and passes all tests on macOS, so the next release will make this port unnecessary, so I guess this can be closed now.

**Comment by bimimicah** [comment]
upstream libbsd is now available on homebrew for macOS ([see](https://github.com/Homebrew/homebrew-core/pull/198648))
